# Generated by Django 4.1 on 2022-09-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=20)),
                ('tipo_carrera', models.CharField(max_length=40)),
                ('plan_de_estudio', models.IntegerField()),
                ('resolucion_rectoral', models.CharField(max_length=20)),
                ('cantidad_asignaturas', models.IntegerField()),
                ('asignaturas', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Comisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=40)),
                ('asignatura', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
                ('comision', models.CharField(max_length=40)),
                ('modalidad', models.CharField(max_length=40)),
                ('horario', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=7)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('titulo_grado', models.CharField(max_length=40)),
                ('titulo_posgrado', models.CharField(max_length=40)),
                ('hs_asignar', models.CharField(max_length=2)),
                ('metodo_alta', models.CharField(max_length=40)),
                ('fecha_alta', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
