# Generated by Django 4.1 on 2022-09-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='docentes',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
