# Generated by Django 4.1 on 2022-09-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0002_asignatura_alter_docentes_dni_alter_docentes_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docentes',
            name='fecha_creacion',
        ),
    ]
