# Generated by Django 4.1 on 2022-09-09 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0003_remove_docentes_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 9, 19, 16, 22, 85393, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
