# Generated by Django 4.1 on 2022-09-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0004_docentes_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='dni',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
