# Generated by Django 4.1 on 2022-09-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0005_alter_docentes_dni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.RenameField(
            model_name='carreras',
            old_name='asignaturas',
            new_name='asignatura',
        ),
    ]
