# Generated by Django 4.1 on 2022-09-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0006_delete_asignatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreras',
            name='asignatura',
        ),
        migrations.CreateModel(
            name='Asiganturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=40)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nomb_doc.carreras')),
            ],
        ),
    ]
