# Generated by Django 4.1 on 2022-09-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0007_remove_carreras_asignatura_asiganturas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asiganturas',
            new_name='Asignaturas',
        ),
    ]
