# Generated by Django 4.1.1 on 2022-09-23 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0008_rename_asiganturas_asignaturas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignaturas',
            old_name='asignatura',
            new_name='anio_semestre',
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='asignatura1',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='asignatura2',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='asignatura3',
            field=models.CharField(default=datetime.datetime(2022, 9, 23, 11, 28, 38, 55200, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='asignatura4',
            field=models.CharField(default=datetime.datetime(2022, 9, 23, 11, 28, 45, 602924, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='asignatura5',
            field=models.CharField(default=datetime.datetime(2022, 9, 23, 11, 28, 52, 310604, tzinfo=datetime.timezone.utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignaturas',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nomb_doc.carreras'),
        ),
    ]
