# Generated by Django 4.1 on 2022-09-24 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0009_rename_asignatura_asignaturas_anio_semestre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisiones',
            options={'verbose_name': 'Comision', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='comisiones',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='comisiones',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='comisiones',
            name='codigo',
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nomb_doc.comisiones'),
        ),
        migrations.AddField(
            model_name='comisiones',
            name='anio',
            field=models.CharField(default=datetime.datetime(2022, 9, 24, 15, 30, 2, 618240, tzinfo=datetime.timezone.utc), max_length=40, verbose_name='Año'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comisiones',
            name='semestre',
            field=models.CharField(default=datetime.datetime(2022, 9, 24, 15, 30, 13, 108173, tzinfo=datetime.timezone.utc), max_length=40, verbose_name='Semestre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comisiones',
            name='comision',
            field=models.CharField(max_length=40, verbose_name='Comision'),
        ),
        migrations.AlterField(
            model_name='comisiones',
            name='horario',
            field=models.CharField(max_length=40, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='comisiones',
            name='modalidad',
            field=models.CharField(max_length=40, verbose_name='Modalidad'),
        ),
        migrations.AlterModelTable(
            name='comisiones',
            table='comision',
        ),
    ]
