# Generated by Django 4.1 on 2022-09-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0011_alter_asignaturas_options_alter_carreras_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreras',
            name='asignaturas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nomb_doc.asignaturas'),
        ),
    ]
