# Generated by Django 4.1 on 2022-09-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0012_carreras_asignaturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreras',
            name='asignaturas',
        ),
    ]
