# Generated by Django 4.1 on 2022-09-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0013_remove_carreras_asignaturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreras',
            name='asignaturas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nomb_doc.asignaturas'),
        ),
    ]
