# Generated by Django 4.1 on 2022-09-29 00:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomb_doc', '0014_carreras_asignaturas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignaturas',
            old_name='asignatura1',
            new_name='asignatura',
        ),
        migrations.RenameField(
            model_name='comisiones',
            old_name='anio',
            new_name='anio_academico',
        ),
        migrations.RenameField(
            model_name='comisiones',
            old_name='semestre',
            new_name='semestre_academico',
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='asignatura2',
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='asignatura3',
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='asignatura4',
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='asignatura5',
        ),
        migrations.RemoveField(
            model_name='asignaturas',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='carreras',
            name='asignaturas',
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nomb_doc.carreras'),
        ),
        migrations.AddField(
            model_name='comisiones',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nomb_doc.asignaturas'),
        ),
        migrations.AddField(
            model_name='comisiones',
            name='codigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nomb_doc.carreras'),
        ),
        migrations.AddField(
            model_name='comisiones',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 9, 29, 0, 45, 12, 98343, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carreras',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
